name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push_docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "${{secrets.DOCKER_HUB_USERNAME}}" --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pizzatime:${{github.sha}}

    - name: Push Docker image
      run: docker push pizzatime:${{github.sha}}

    - name: Tag Docker image
      run: docker tag pizzatime:${{github.sha}} bryanlrx/pizzatime:latest

    - name: Push latest tag
      run: docker bryanlrx/pizzatime:latest
